version: '3'

services:
  app:
    user: '${UID}:${GID}'
    build: .
    entrypoint: dockerize -wait tcp://db:5432 -timeout 40s ./.docker/entrypoint.sh
    container_name: store-api-app
    ports:
      - 8091:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    user: '${UID}:${GID}'
    build: .docker/postgres
    container_name: store-api-db
    restart: always
    tty: true
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=store
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data

  grpc-test:
    image: gusaul/grpcox:latest
    ports:
      - 6969:6969
